<?php

include_once 'atrium_accountant.features.inc';

/**
 * Implements hook_init().
 */
function atrium_accountant_init() {
  drupal_add_css(drupal_get_path('module', 'atrium_accountant') . '/css/atrium_accountant.css');
}

/**
 * Implements of hook_help().
 */
function atrium_accountant_help($path) {
  // Sitewide help.
  if ($path == 'admin/help#atrium_accountant') {
    return  '<h3>'. t('Accountant') . '</h3>' .
            '<p>' . t('Atrium Accountant is a simple accounting feature for OpenAtrium which lets you take care of your accounts and income/expense transactions.') . '</p>' .
            '<p>' . t('To add accounts/transactions navigate to the Accountant feature and click the "Add account" or "Add transacion" button.') .'</p>';
  }
  // Contextual help.
  if (context_isset('context', 'spaces-feature-atrium_accountant')) {
    // On account creation form.
    if ($path == 'node/add/account') {
      return  '<h3>' . t('Account') .'</h3>' .
              '<p>'  . t('Create an account in this group. This account will be available on later transacion creations.') .'</p>';
    }
    // On transaction creation form.
    elseif ($path == 'node/add/transaction') {
      return  '<h3>'. t('Transaction') .'</h3>';
              '<p>'.  t('Create a transaction in this group. This transaction will change the balance of the related account based on its type.') .'</p>';
    }
  }
}
